# Generated by Django 5.0.1 on 2024-01-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ottapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
